name: Run End-to-End Integration Tests

on:
  push:
    branches: [master]
    paths:
      - "components/ui/**"
      - "packages/client/**"
      - "packages/browser-test-runner/**"
  pull_request:
    branches: [master]
    paths:
      - "components/ui/**"
      - "packages/client/**"
      - "packages/browser-test-runner/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Install packages
        run: pnpm install
      - name: Build all dependencies
        run: pnpm build:deps
      - name: Install Playwright
        working-directory: packages/browser-test-runner
        run: pnpm playwright install --with-deps
      - name: Write .env.local for client
        uses: DamianReeves/write-file-action@master
        with:
          path: packages/client/.env.local
          contents: |
            VITE_API_URL=http://local.revolt.chat:8000
          write-mode: overwrite
      - name: Run services in background
        run: |
          docker-compose up -d
      - name: Run client in background
        run: |
          pnpm dev &
      - name: Wait 15s for everything to start
        run: sleep 15s
        shell: bash
      - name: Run tests
        working-directory: packages/browser-test-runner
        run: pnpm playwright test integration
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: packages/browser-test-runner/playwright-report
